# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-17 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '片区',
                'verbose_name_plural': '片区',
                'permissions': (('ischengxi', '是否是城西'), ('ischengdong', '是否是城东'), ('ischengnan', '是否是城南'), ('isgaoxin', '是否是高新'), ('isyouxian', '是否是游仙'), ('iskechuangyuan', '是否是科创园')),
            },
        ),
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.IntegerField(default=0)),
                ('class2', models.IntegerField(default=0)),
                ('class3', models.IntegerField(default=0)),
                ('parkingLotNumber', models.IntegerField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('passTime', models.DateTimeField(blank=True, null=True)),
                ('isLastest', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
                ('createUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createUser', to=settings.AUTH_USER_MODEL)),
                ('passUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '泊位数',
                'verbose_name_plural': '泊位数',
                'ordering': ['createTime'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户和片区的对应关系',
                'verbose_name_plural': '用户和片区的对应关系',
            },
        ),
    ]
