# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-17 05:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowBerth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.IntegerField(default=0)),
                ('class2', models.IntegerField(default=0)),
                ('class3', models.IntegerField(default=0)),
                ('parkingLotNumber', models.IntegerField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('passTime', models.DateTimeField(blank=True, null=True)),
                ('isLastest', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
                ('createUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createUser', to=settings.AUTH_USER_MODEL)),
                ('passUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '发布泊位数',
                'verbose_name_plural': '发布泊位数',
                'ordering': ['createTime'],
            },
        ),
        migrations.AlterModelOptions(
            name='berth',
            options={'ordering': ['createTime'], 'verbose_name': '待审核泊位数', 'verbose_name_plural': '待审核泊位数'},
        ),
        migrations.RemoveField(
            model_name='berth',
            name='isLastest',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='passTime',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='passUser',
        ),
        migrations.AlterField(
            model_name='berth',
            name='createUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
