# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-17 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181017_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='showberth',
            name='inRoadTotalNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='showberth',
            name='createTime',
            field=models.DateTimeField(),
        ),
    ]
