# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-18 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181017_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='showberth',
            name='diciInclass1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showberth',
            name='diciInclass2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showberth',
            name='diciInclass3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showberth',
            name='diciTotalNumber',
            field=models.IntegerField(default=0),
        ),
    ]
