# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-18 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181018_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='diciInclass1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='berth',
            name='diciInclass2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='berth',
            name='diciInclass3',
            field=models.IntegerField(default=0),
        ),
    ]
