# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-18 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181018_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'permissions': (('can_edit', '是否可以编辑片区信息'),), 'verbose_name': '片区', 'verbose_name_plural': '片区'},
        ),
        migrations.AlterModelOptions(
            name='berth',
            options={'ordering': ['createTime'], 'permissions': (('can_review', '是否可以审核'),), 'verbose_name': '待审核泊位数', 'verbose_name_plural': '待审核泊位数'},
        ),
    ]
