# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181018_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='controlclass1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='berth',
            name='controlclass2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='berth',
            name='controlclass3',
            field=models.IntegerField(default=0),
        ),
    ]
