# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-24 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20181023_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoufeiyuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maninclass1', models.IntegerField(default=0)),
                ('maninclass2', models.IntegerField(default=0)),
                ('maninclass3', models.IntegerField(default=0)),
                ('manTotalNumber', models.IntegerField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('passTime', models.DateTimeField(blank=True, null=True)),
                ('isPassed', models.BooleanField(default=False)),
                ('isLastest', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
                ('createUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createShoufeiyuanUser', to=settings.AUTH_USER_MODEL)),
                ('passUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passShoufeiyuanUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '待审核收费员数',
                'verbose_name_plural': '待审核收费员数',
            },
        ),
    ]
