# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-24 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shoufeiyuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='areaname',
            field=models.CharField(default='停车公司', max_length=100),
        ),
    ]
