# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181025_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='isLastest',
        ),
    ]
