# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-29 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181029_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='park',
            options={'permissions': (('can_edit_park', '是否可以编辑停车场信息'),), 'verbose_name': '停车场', 'verbose_name_plural': '停车场'},
        ),
    ]
