# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-29 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181029_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='explain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
