# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-26 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_pos_sim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pos',
            options={'permissions': (('can_edit_hardware', '是否可以编辑硬件信息'),), 'verbose_name': 'POS管理', 'verbose_name_plural': 'POS管理'},
        ),
        migrations.AlterModelOptions(
            name='sim',
            options={'verbose_name': 'SIM管理', 'verbose_name_plural': 'SIM管理'},
        ),
    ]
