# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-28 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181126_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='status',
            field=models.CharField(choices=[('城西片区', '城西片区'), ('城东片区', '城东片区'), ('城南片区', '城南片区'), ('高新片区', '高新片区'), ('游仙片区', '游仙片区'), ('科创园片区', '科创园片区'), ('库存中', '库存中'), ('无法使用', '无法使用'), ('已遗失', '已遗失'), ('其他', '其他')], default='库存中', max_length=10),
        ),
    ]
