# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181128_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='people',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
