# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_sim_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='SIM_Company',
            field=models.CharField(choices=[('移动', '移动'), ('联通', '联通'), ('电信', '电信')], max_length=10),
        ),
    ]
