# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-28 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181128_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='people',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
